
public class User {
	String USERID, USERNAME, USERSHORTNAME, BANKCODE, BRANCHCODE, DEPARTMENTCODE, LANGUAGE, ADMINISTRATOR,
	DEVELOPER, INTERNALRS2, STATUS, PASSWORDDATE, LASTLOGON, LASTLOGOFF, ACCESSGROUPS, VALIDINSTITUTIONS,
	DEFAULTINSTITUTION, SHOWTIP, AUDITTRAIL, PASS_WORD, MODULEACCESS, WRONGPASSWORDCOUNT;
public User(String USERID, String USERNAME, String USERSHORTNAME, String BANKCODE, String BRANCHCODE, String DEPARTMENTCODE, String LANGUAGE, String ADMINISTRATOR,
		String DEVELOPER, String INTERNALRS2, String STATUS, String PASSWORDDATE, String LASTLOGON, String LASTLOGOFF, String ACCESSGROUPS, String VALIDINSTITUTIONS,
		String DEFAULTINSTITUTION, String SHOWTIP, String AUDITTRAIL, String PASS_WORD, String MODULEACCESS, String WRONGPASSWORDCOUNT){
		this.USERID = USERID;
		this.USERNAME = USERNAME;
		this.USERSHORTNAME = USERSHORTNAME;
		this.BANKCODE = BANKCODE;
		this.BRANCHCODE = BRANCHCODE;
		this.DEPARTMENTCODE = DEPARTMENTCODE;
		this.LANGUAGE = LANGUAGE;
		this.ADMINISTRATOR = ADMINISTRATOR;
		this.DEVELOPER = DEVELOPER;
		this.INTERNALRS2 = INTERNALRS2;
		this.STATUS = STATUS;
		this.PASSWORDDATE = PASSWORDDATE;
		this.LASTLOGON = LASTLOGON;
		this.LASTLOGOFF = LASTLOGOFF;
		this.ACCESSGROUPS = ACCESSGROUPS;
		this.VALIDINSTITUTIONS = VALIDINSTITUTIONS;
		this.DEFAULTINSTITUTION = DEFAULTINSTITUTION;
		this.SHOWTIP = SHOWTIP;
		this.AUDITTRAIL = AUDITTRAIL;
		this.PASS_WORD = PASS_WORD;
		this.MODULEACCESS = MODULEACCESS;
		this.WRONGPASSWORDCOUNT = WRONGPASSWORDCOUNT;	
}
//calling this method when insert for user is required
public String returnInsert(){
	//This allows to avoid bug for values as null in database in this field
	if(WRONGPASSWORDCOUNT == null){
		WRONGPASSWORDCOUNT = "0";
	}
	
	String insert = String.format("INSERT INTO bw3.SYS_USER_INFORMATION ( USERID , USERNAME , USERSHORTNAME , BANKCODE , BRANCHCODE , DEPARTMENTCODE , LANGUAGE , ADMINISTRATOR , DEVELOPER , INTERNALRS2 , STATUS , PASSWORDDATE , LASTLOGON , LASTLOGOFF , ACCESSGROUPS , VALIDINSTITUTIONS , DEFAULTINSTITUTION , SHOWTIP , AUDITTRAIL , PASS_WORD , MODULEACCESS , WRONGPASSWORDCOUNT ) VALUES(  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  %s,  %s,  %s,  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s',  '%s')"
	,USERID, USERNAME, USERSHORTNAME, BANKCODE, BRANCHCODE, DEPARTMENTCODE, LANGUAGE, ADMINISTRATOR,
	DEVELOPER, INTERNALRS2, STATUS, "to_date('"+PASSWORDDATE+"','yyyy-mm-dd hh24:mi:ss')", "to_date('"+LASTLOGON+"','yyyy-mm-dd hh24:mi:ss')", "to_date('"+LASTLOGOFF+"','yyyy-mm-dd hh24:mi:ss')", ACCESSGROUPS, VALIDINSTITUTIONS,
	DEFAULTINSTITUTION, SHOWTIP, AUDITTRAIL, PASS_WORD, MODULEACCESS, WRONGPASSWORDCOUNT);

	//returning insert statement
	return insert;
}

public String updateInstitutionList(){
	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET VALIDINSTITUTIONS = '%s' WHERE USERID = '%s'",VALIDINSTITUTIONS,USERID);
	return insert;
}
//public String updateInstitutionListx(){
//	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET VALIDINSTITUTIONS = '%s'",VALIDINSTITUTIONS);
//	return insert;
//}

public String updateDefaultInstitution(){
	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET DEFAULTINSTITUTION = '%s' WHERE USERID = '%s'",DEFAULTINSTITUTION,USERID);
	return insert;
}
public String updateModuleAccess(){
	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET MODULEACCESS = '%s' WHERE USERID = '%s'",MODULEACCESS,USERID);
	return insert;
}
public String updateAccessGroups(){
	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET ACCESSGROUPS = '%s' WHERE USERID = '%s'",ACCESSGROUPS,USERID);
	return insert;
}
public String updateEverything(){
	
	String insert = String.format("UPDATE bw3.SYS_USER_INFORMATION SET USERID = '%s', USERNAME= '%s' , USERSHORTNAME= '%s' , BANKCODE= '%s' , BRANCHCODE= '%s' , DEPARTMENTCODE= '%s' ,"+
	" LANGUAGE= '%s' , ADMINISTRATOR= '%s' , DEVELOPER= '%s' , INTERNALRS2= '%s' , STATUS= '%s' , ACCESSGROUPS= '%s' , VALIDINSTITUTIONS= '%s' , DEFAULTINSTITUTION= '%s' , SHOWTIP= '%s'"+
	" , AUDITTRAIL= '%s' , PASS_WORD= '%s' ,MODULEACCESS='%s', WRONGPASSWORDCOUNT= '%s',PASSWORDDATE = to_date('"+PASSWORDDATE+"','yyyy-mm-dd hh24:mi:ss'), LASTLOGON = to_date('"+LASTLOGON+"','yyyy-mm-dd hh24:mi:ss'), LASTLOGOFF = to_date('"+LASTLOGOFF+"','yyyy-mm-dd hh24:mi:ss')"+
	" WHERE USERID = '%s'",
			USERID , USERNAME , USERSHORTNAME , BANKCODE , BRANCHCODE , DEPARTMENTCODE , LANGUAGE , ADMINISTRATOR , DEVELOPER , INTERNALRS2 , STATUS , ACCESSGROUPS , VALIDINSTITUTIONS , DEFAULTINSTITUTION , SHOWTIP , AUDITTRAIL , PASS_WORD , MODULEACCESS , WRONGPASSWORDCOUNT,USERID);
	return insert;
}

}
